name: Check for new versions of the Docker image

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  check-version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get latest Docker Hub tag
      id: latest_tag
      uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.1
      with:
        org: 'daskdev'
        repo: 'dask'
    - name: Update version
      run: |
        export NEW_DASK_VERSION=${{ steps.latest_tag.outputs.tag }}
        export CURRENT_DASK_VERSION=$(cat dask/Chart.yaml | grep appVersion | awk '{ print $2 }')
        find dask -type f -exec sed -i "s/${CURRENT_DASK_VERSION//./\.}/${NEW_DASK_VERSION//./\.}/g" {} \;
        git add . && git diff-index --quiet HEAD
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Dask Version
        title: 'Update Dask Version'
        body: |
          A new Dask docker image version has been detected. Updation chart version.
